At/readme update
COMP4350/Servus pull request #152
Opened 2021-04-09 15:45 UTC by cadenchabot

Updated readme with setup and run instructions.

2021-04-09 20:01 UTC, RikiZimbakov requested changes
Other then my one change looks good. Way to go sport!

2021-04-09 20:01 UTC, RikiZimbakov commented on README.md
> +> At your service
please change this back
```suggestion
> At your Servus
```

2021-04-09 21:16 UTC, RikiZimbakov approved these changes

2021-04-11 02:11 UTC, Arvind-Maan commented on README.md
> +-   Go to <https://comp4350.github.io/Servus/>
change to http://servus.pw

2021-04-11 21:50 UTC, merged